services:
  auth-api:
    container_name: auth-api
    build:
      context: ./auth-api
      dockerfile: Dockerfile
    env_file:
      - ./auth-api/.env.development
      - .env.development
    environment:
      - NODE_ENV=development
    depends_on:
      - auth-base
    networks:
      - auth-network
    volumes:
      - ./auth-api:/app
      - /app/node_modules
    command: bun --watch src/index.ts

  auth-base:
    container_name: auth-base
    image: ghcr.io/muchobien/pocketbase:latest
    ports:
      - "8090:8090"
    volumes:
      - auth_data:/pb_data
    environment:
      - POCKETBASE_PORT=8090
      - POCKETBASE_BIND=0.0.0.0:8090
    networks:
      - auth-network

  bisia-api:
    container_name: bisia-api
    build:
      context: ./bisia-api
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    env_file:
      - ./bisia-api/.env.development
      - .env.development
    environment:
      - NODE_ENV=development
    depends_on:
      - bisia-base
    networks:
      - auth-network
    volumes:
      - ./bisia-api:/app
      - /app/node_modules
    command: bun --watch src/index.ts

  bisia-base:
    container_name: bisia-base
    image: ghcr.io/muchobien/pocketbase:latest
    ports:
      - "8091:8090"
    volumes:
      - bisia_data:/pb_data
    environment:
      - POCKETBASE_PORT=8090
      - POCKETBASE_BIND=0.0.0.0:8090
    networks:
      - auth-network

  bisia-frontend:
    container_name: bisia-frontend
    build:
      context: ./bisia-frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./bisia-frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - auth-network

networks:
  auth-network:
    driver: bridge

volumes:
  auth_data:
    # driver: local
    external: true
    name: docker-compose_auth_data
  bisia_data:
    # driver: local
    external: true
    name: docker-compose_bisia_data
