version: "3.8"

services:
  # Auth API
  auth-api:
    container_name: auth-api
    build:
      context: ./auth-api
      dockerfile: Dockerfile
    env_file:
      - ./auth-api/.env.production
      - .env.production
    environment:
      - NODE_ENV=production
    depends_on:
      - auth-base
    networks:
      - auth-network

  # Auth Base (PocketBase per Auth)
  auth-base:
    container_name: auth-base
    image: ghcr.io/muchobien/pocketbase:latest
    ports:
      - "8090:8090"
    volumes:
      - auth_data:/pb_data
    environment:
      - POCKETBASE_PORT=8090
      - POCKETBASE_BIND=0.0.0.0:8090
    networks:
      - app_network
    restart: unless-stopped

  # Bisia API
  bisia-api:
    container_name: bisia-api
    build:
      context: ./bisia-api
      dockerfile: Dockerfile
    env_file:
      - ./bisia-api/.env.production
      - .env.production
    environment:
      - NODE_ENV=production
    depends_on:
      - auth-api
      - bisia-base
    networks:
      - auth-network

  # Bisia Base (PocketBase per Bisia)
  bisia-base:
    container_name: bisia-base-prod
    image: ghcr.io/muchobien/pocketbase:latest
    ports:
      - "8091:8090"
    volumes:
      - bisia_data:/pb_data
    environment:
      - POCKETBASE_PORT=8090
      - POCKETBASE_BIND=0.0.0.0:8090
    networks:
      - app_network
    restart: unless-stopped

  # Frontend
  bisia-frontend:
    container_name: bisia-frontend-prod
    build:
      context: ./bisia-frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NODE_ENV=production
      - VITE_AUTH_API_URL=${AUTH_API_URL}
      - VITE_BISIA_API_URL=${BISIA_API_URL}
    depends_on:
      - auth-api
      - bisia-api
    networks:
      - app_network
    restart: unless-stopped

networks:
  app_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16

volumes:
  auth_data:
    driver: local
  bisia_data:
    driver: local
  mail_logs:
